name: lab03_ml_2026_01
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - pyreadstat
  - pyyaml
  - matplotlib
  - seaborn
  - jupyter
  - pip
